"""Rebuild docs/ladder_summary.md from the current code: the Cox model ladder on every synthetic scenario.

    python scripts/build_ladder_summary.py [--out docs/ladder_summary.md] [--bootstrap 200]

Every scenario is generated with the default seed and size, and every step is evaluated with
patient-grouped five-fold cross-validation (kairos.evaluation.ladder.evaluate_ladder). Bootstrap
intervals are computed for core_plus_both, the step whose calibration and discrimination are tabled.
Metrics are on pooled landmark rows, at the 5-year horizon. Synthetic and illustrative.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from kairos.evaluation.ladder import evaluate_ladder  # noqa: E402
from kairos.modelling.modules import load_model_config  # noqa: E402
from kairos.simulation.generators import GENERATOR_VERSION, generate_cohort  # noqa: E402
from kairos.simulation.scenarios import get_scenario, list_scenarios  # noqa: E402

STEPS = ["reference", "core", "core_plus_biomarkers", "core_plus_anticoagulant", "core_plus_both", "core_without_serial_echo"]
TAU = 5.0
AC_PREFIXES = ("ac_", "on_antiplatelet")


def _svd5(results):
    d = results[(results["state"] == "svd") & (results["horizon_years"] == TAU)
                & (results["weighting"] == "pooled landmark rows")]
    return d.set_index("step")


def _f(row, key: str, fmt: str) -> str:
    """A formatted metric, or n/a where the evaluator withheld it (too few events to support it)."""
    try:
        v = float(row[key])
    except (KeyError, TypeError, ValueError):
        return "n/a"
    return format(v, fmt) if v == v else "n/a"


def _ac(coefs: dict, cut: float = 0.05) -> dict:
    return {k: round(float(v), 2) for k, v in coefs.items() if k.startswith(AC_PREFIXES) and abs(v) >= cut}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(ROOT / "docs" / "ladder_summary.md"))
    ap.add_argument("--bootstrap", type=int, default=200)
    ap.add_argument("--seed", type=int, default=20260916)
    args = ap.parse_args()
    cfg = load_model_config()
    brier, calib, modules = [], [], []
    for name, variant in list_scenarios():
        key = name + (f"/{variant}" if variant else "")
        cohort = generate_cohort(get_scenario(name, variant), seed=args.seed)
        plain = _svd5(evaluate_ladder(cohort, cfg, n_boot=0, steps=[s for s in STEPS if s != "core_plus_both"],
                                      extras=False).results)
        full = evaluate_ladder(cohort, cfg, n_boot=args.bootstrap, steps=["core_plus_both"], extras=True)
        svd_both = _svd5(full.results)
        both = svd_both.loc["core_plus_both"] if "core_plus_both" in svd_both.index else {}
        steps = {**{s: plain.loc[s] for s in plain.index}, "core_plus_both": both}
        brier.append(f"| {key} | " + " | ".join(_f(steps.get(s, {}), "brier", ".4f") for s in STEPS)
                     + f" | {_f(both, 'n_events', '.0f')} |")
        calib.append(f"| {key} | {_f(both, 'observed', '.3f')} | {_f(both, 'mean_predicted', '.3f')} | "
                     f"{_f(both, 'obs_minus_pred', '.3f')} | {_f(both, 'cal_slope_logit', '.2f')} | "
                     f"{_f(both, 'auc', '.2f')} ({_f(both, 'auc_lo', '.2f')}-{_f(both, 'auc_hi', '.2f')}) | {_f(both, 'ipa', '.3f')} |")
        dropped = (both.get("modules_dropped") if len(both) else None) or "none"
        thromb = (full.secondary or {}).get("coefficients", {})
        modules.append(f"- **{key}**: modules off: {dropped}; SVD anticoagulant coefficients: "
                       f"{_ac(full.coefficients.get('core_plus_both', {}))}; thrombosis outcome: {_ac(thromb)}")
        print(f"{key}: done", flush=True)
    lines = [f"Generated by `scripts/build_ladder_summary.py` (generator {GENERATOR_VERSION}, seed {args.seed}, "
             f"{args.bootstrap} bootstrap replicates for core_plus_both). Pooled landmark rows, synthetic scenarios.", "",
             "### IPCW Brier at 5 years (lower is better), synthetic scenarios", "",
             "| scenario | " + " | ".join(STEPS) + " | n events (5 y) |", "|" + "---|" * (len(STEPS) + 2), *brier, "",
             "### Calibration and discrimination of core_plus_both at 5 years", "",
             "| scenario | observed | mean predicted | cal-in-large | cal slope | AUC (95% CI) | IPA |",
             "|---|---|---|---|---|---|---|", *calib, "",
             "### Module availability and anticoagulant coefficients", "",
             "Coefficients with an absolute value of at least 0.05 on the log-hazard scale; synthetic, "
             "confounded by construction in some scenarios, and never a treatment effect.", "", *modules]
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
